version: '3.9'
services:
  pgdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1235789
      - POSTGRES_DB=askme
    ports: 
      - "5432:5432"  
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=postgres://postgres:1235789@pgdb:5432/askme?sslmode=disable  
    depends_on:
      - pgdb
    entrypoint: ["/app/wait.sh","pgdb:5432","--","/app/start.sh"]
    command: ["/app/main"]

