// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1
// source: FcmToken.sql

package db

import (
	"context"
)

const createFcmToken = `-- name: CreateFcmToken :one
INSERT INTO "FcmToken" (id,user_id,fcm_token,is_valid) VALUES ($1, $2, $3,$4) RETURNING id, user_id, fcm_token, is_valid, created_at
`

type CreateFcmTokenParams struct {
	ID       int32  `json:"id"`
	UserID   int32  `json:"user_id"`
	FcmToken string `json:"fcm_token"`
	IsValid  bool   `json:"is_valid"`
}

func (q *Queries) CreateFcmToken(ctx context.Context, arg CreateFcmTokenParams) (FcmToken, error) {
	row := q.db.QueryRowContext(ctx, createFcmToken,
		arg.ID,
		arg.UserID,
		arg.FcmToken,
		arg.IsValid,
	)
	var i FcmToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.IsValid,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFcmToken = `-- name: DeleteFcmToken :one
DELETE FROM "FcmToken" WHERE
id=$1 RETURNING id, user_id, fcm_token, is_valid, created_at
`

func (q *Queries) DeleteFcmToken(ctx context.Context, id int32) (FcmToken, error) {
	row := q.db.QueryRowContext(ctx, deleteFcmToken, id)
	var i FcmToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.IsValid,
		&i.CreatedAt,
	)
	return i, err
}

const deleteFcmTokenByUserId = `-- name: DeleteFcmTokenByUserId :many
DELETE FROM "FcmToken" WHERE user_id = $1
RETURNING id, user_id, fcm_token, is_valid, created_at
`

func (q *Queries) DeleteFcmTokenByUserId(ctx context.Context, userID int32) ([]FcmToken, error) {
	rows, err := q.db.QueryContext(ctx, deleteFcmTokenByUserId, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FcmToken{}
	for rows.Next() {
		var i FcmToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.FcmToken,
			&i.IsValid,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFcmTokenById = `-- name: GetFcmTokenById :one
SELECT id, user_id, fcm_token, is_valid, created_at FROM "FcmToken" WHERE id = $1
`

func (q *Queries) GetFcmTokenById(ctx context.Context, id int32) (FcmToken, error) {
	row := q.db.QueryRowContext(ctx, getFcmTokenById, id)
	var i FcmToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.IsValid,
		&i.CreatedAt,
	)
	return i, err
}

const getFcmTokenUserId = `-- name: GetFcmTokenUserId :one
SELECT id, user_id, fcm_token, is_valid, created_at FROM "FcmToken" WHERE user_id = $1 and is_valid = 1
`

func (q *Queries) GetFcmTokenUserId(ctx context.Context, userID int32) (FcmToken, error) {
	row := q.db.QueryRowContext(ctx, getFcmTokenUserId, userID)
	var i FcmToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.IsValid,
		&i.CreatedAt,
	)
	return i, err
}

const updateFcmToken = `-- name: UpdateFcmToken :one
UPDATE "FcmToken" 
SET is_valid=$2
WHERE id = $1
RETURNING id, user_id, fcm_token, is_valid, created_at
`

type UpdateFcmTokenParams struct {
	ID      int32 `json:"id"`
	IsValid bool  `json:"is_valid"`
}

func (q *Queries) UpdateFcmToken(ctx context.Context, arg UpdateFcmTokenParams) (FcmToken, error) {
	row := q.db.QueryRowContext(ctx, updateFcmToken, arg.ID, arg.IsValid)
	var i FcmToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.FcmToken,
		&i.IsValid,
		&i.CreatedAt,
	)
	return i, err
}
