// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"database/sql"
	"time"
)

type Answer struct {
	ID         int32        `json:"id"`
	UserID     int32        `json:"user_id"`
	QuestionID int32        `json:"question_id"`
	Content    string       `json:"content"`
	CreatedAt  sql.NullTime `json:"created_at"`
	UpdatedAt  time.Time    `json:"updated_at"`
}

type Question struct {
	ID        int32        `json:"id"`
	UserID    int32        `json:"user_id"`
	Content   string       `json:"content"`
	CreatedAt sql.NullTime `json:"created_at"`
	UpdatedAt time.Time    `json:"updated_at"`
}

type User struct {
	ID           int32          `json:"id"`
	Username     string         `json:"username"`
	Email        string         `json:"email"`
	PasswordHash sql.NullString `json:"password_hash"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    time.Time      `json:"updated_at"`
}
