// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.19.1

package db

import (
	"context"
)

type Querier interface {
	AnswerDelete(ctx context.Context, id int32) error
	CreateAnswer(ctx context.Context, arg CreateAnswerParams) (Answer, error)
	CreateQuestion(ctx context.Context, arg CreateQuestionParams) (Question, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteAnswerByQuestionId(ctx context.Context, questionID int32) error
	GetAnswerByID(ctx context.Context, id int32) (Answer, error)
	GetAnswerForUpdate(ctx context.Context, id int32) (Answer, error)
	GetAnswersByQuestionID(ctx context.Context, arg GetAnswersByQuestionIDParams) ([]Answer, error)
	GetQuestionByID(ctx context.Context, id int32) (Question, error)
	GetQuestionForUpdate(ctx context.Context, id int32) (Question, error)
	GetQuestionsByUserID(ctx context.Context, arg GetQuestionsByUserIDParams) ([]Question, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int32) (User, error)
	QuestionDelete(ctx context.Context, id int32) error
	UpdateAnswersByQuestionID(ctx context.Context, arg UpdateAnswersByQuestionIDParams) (Answer, error)
	UpdateQuestionById(ctx context.Context, arg UpdateQuestionByIdParams) (Question, error)
}

var _ Querier = (*Queries)(nil)
